name: Framework CI/CD release pipeline

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '*.md'
      - 'banner.txt'
      - 'docs/**'
      - 'LICENSE'
      - 'src/templates/**'
      - 'setup.sh'

jobs:
  run:
    env:
      REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
      REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

      SONAR_URL: ${{ secrets.SONAR_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - name: Download project files
      uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: corretto
        java-version: 21

    - name: Build and Test
      run: ./build.sh

    - name: Code Analysis
      run: ./codeAnalysis.sh

    - name: Libraries Analysis
      run: ./librariesAnalysis.sh

    - name: Publish
      run: ./publish.sh

    - name: Notify
      if: always()
      run: ./notify.sh "release" "${{ job.status }}"